CREATE PROC SP_CTHD
@X VARCHAR(8)
AS
SELECT PS.PHIEU , NGAY, LOAI, TENVT ,
  SOLUONG ,DONGIA , TRIGIA = SOLUONG *DONGIA 
  FROM PHATSINH  PS, CT_PHATSINH CT, VATTU VT
  WHERE PS.PHIEU  =@X AND PS.PHIEU = CT.PHIEU 
    AND CT.MAVT = VT.MAVT 
  
  
  EXEC SP_CTHD 'PN01'
  
   
  CREATE VIEW V_TK_HD_NV
  AS
    SELECT NV.MANV, HO+ ' '+ TEN AS HOTEN, COUNT (*) AS SOLG_HD
      FROM PHATSINH PS, NHANVIEN NV
      WHERE PS.MANV=NV.MANV 
      GROUP BY NV.MANV, HO+ ' '+ TEN
      
  CREATE PROC SP_TK_HD_THANG
  @loai VARCHAR (1), @nam INT
  AS
    SELECT MONTH(NGAY) AS THANG, SOLG_HD= COUNT (*)
      FROM PHATSINH 
      WHERE LOAI =@loai AND YEAR (NGAY) = @nam 
      GROUP BY MONTH(NGAY)
      
     EXEC SP_TK_HD_THANG 'N', 2014
     
  
  CREATE PROC SP_TK_TGHD_NV
  @nam INT, @TGTG_MIN INT
  AS
  SELECT NV.MANV, HO+ ' '+ TEN AS HOTEN, SUM (SOLUONG*DONGIA) AS TG_TRIGIA_HD
    FROM PHATSINH PS, CT_PHATSINH CT, NHANVIEN NV
    WHERE YEAR (NGAY) = @nam AND LOAI ='X' AND PS.MANV=NV.MANV 
       AND PS.PHIEU=CT.PHIEU
    GROUP BY    NV.MANV, HO+ ' '+ TEN 
         HAVING SUM (SOLUONG*DONGIA) > @TGTG_MIN
    
    EXEC SP_TK_TGHD_NV 2013, 30000000
    
   CREATE PROC SP_TK_TOPHD_NV
    @loai VARCHAR (1), @n INT
  AS
    SELECT NV.MANV, HO+ ' '+ TEN AS HOTEN, SOLG_HD= COUNT (*)
      INTO #T
      FROM PHATSINH PS, NHANVIEN NV
      WHERE LOAI =@loai AND NV.MANV=PS.MANV 
      GROUP BY NV.MANV, HO+ ' '+ TEN  
    
    SET ROWCOUNT @N
    SELECT  #T.*
      FROM #T
      ORDER BY SOLG_HD DESC 
      
      EXEC SP_TK_TOPHD_NV 'N', 1